# Generated by Django 4.0.3 on 2024-04-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_car_a_alter_car_user_alter_customtoken_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='Car',
        ),
    ]
