# Generated by Django 4.0.3 on 2024-04-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_alter_car_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table=None,
        ),
    ]
