# Generated by Django 4.0.3 on 2024-04-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0008_car'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table=None,
        ),
    ]
